#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

set -e

git checkout master && \
git pull && \
git checkout development && \
git pull && \
"${SCRIPTPATH}"/mvnw jgitflow:release-start -am -pl :jsystemd-core,:jsystemd-spring-boot-starter && \
"${SCRIPTPATH}"/mvnw jgitflow:release-finish -am -pl :jsystemd-core,:jsystemd-spring-boot-starter
