#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

set -e

"${SCRIPTPATH}"/mvnw clean package site site:site -P !sample -am -pl :jsystemd-core,:jsystemd-spring-boot-starter --debug
